/**
 * NPM Command Definitions
 * Contains all 65+ npm commands with their aliases and parameters
 */

export interface CommandParameter {
  name: string;
  aliases?: string[];
  description: string;
  requiresValue?: boolean;
}

export interface NpmCommand {
  name: string;
  aliases?: string[];
  description: string;
  parameters: CommandParameter[];
  mockOutput: string;
}

export const NPM_COMMANDS: NpmCommand[] = [
  {
    name: 'init',
    aliases: ['create', 'innit'],
    description: 'Create a package.json file',
    parameters: [
      { name: '-y', aliases: ['--yes'], description: 'Use default values', requiresValue: false },
      { name: '-f', aliases: ['--force'], description: 'Force creation', requiresValue: false },
      { name: '--scope', description: 'Set package scope (e.g., @mycompany)', requiresValue: true },
      { name: '--init-author-name', description: 'Set author name', requiresValue: true },
      { name: '--init-author-email', description: 'Set author email (works with name)', requiresValue: true },
      { name: '--init-author-url', description: 'Set author URL (works with name)', requiresValue: true },
      { name: '--init-license', description: 'Set default license', requiresValue: true },
      { name: '--init-version', description: 'Set default version', requiresValue: true },
      { name: '--init-type', description: 'Set package type (commonjs or module)', requiresValue: true },
      { name: '--init-module', description: 'Path to custom init script', requiresValue: true },
      { name: '--init-private', description: 'Mark package as private', requiresValue: false },
      { name: '-w', aliases: ['--workspace'], description: 'Initialize in workspace', requiresValue: true },
      { name: '--workspaces', description: 'Initialize all workspaces', requiresValue: false },
      { name: '--include-workspace-root', description: 'Include workspace root', requiresValue: false },
    ],
    mockOutput: 'Wrote to package.json:\n\n{\n  "name": "my-project",\n  "version": "1.0.0",\n  "description": "",\n  "main": "index.js",\n  "scripts": {\n    "test": "echo \\"Error: no test specified\\" && exit 1"\n  },\n  "keywords": [],\n  "author": "",\n  "license": "ISC",\n  "type": "commonjs"\n}',
  },
  {
    name: 'install',
    aliases: ['i', 'add', 'in', 'ins', 'inst', 'insta', 'instal', 'isnt', 'isnta', 'isntal', 'isntall'],
    description: 'Install packages',
    parameters: [
      // Save options
      { name: '--save', aliases: ['-S'], description: 'Save to dependencies (default)', requiresValue: false },
      { name: '--save-prod', description: 'Save to dependencies (default)', requiresValue: false },
      { name: '--no-save', description: 'Prevent saving to package.json', requiresValue: false },
      { name: '--save-dev', aliases: ['-D'], description: 'Save to devDependencies', requiresValue: false },
      { name: '--save-exact', aliases: ['-E'], description: 'Save exact version', requiresValue: false },
      { name: '--save-optional', description: 'Save to optionalDependencies', requiresValue: false },
      { name: '--save-peer', description: 'Save to peerDependencies', requiresValue: false },
      { name: '--save-bundle', description: 'Save to bundleDependencies', requiresValue: false },
      // Installation location
      { name: '--global', aliases: ['-g'], description: 'Install globally', requiresValue: false },
      // Installation strategy
      { name: '--install-strategy', description: 'Installation strategy (hoisted, nested, shallow, linked)', requiresValue: true },
      { name: '--legacy-bundling', description: 'Install with npm v2 bundling behavior', requiresValue: false },
      { name: '--global-style', description: 'Install packages into prefix without flattening', requiresValue: false },
      { name: '--prefer-dedupe', description: 'Prefer deduping over installing', requiresValue: false },
      // Dependencies filtering
      { name: '--omit', description: 'Omit dependency types (dev, optional, peer)', requiresValue: true },
      { name: '--include', description: 'Include dependency types', requiresValue: true },
      // Lock file
      { name: '--package-lock', description: 'Use package-lock.json (default true)', requiresValue: false },
      { name: '--no-package-lock', description: 'Don\'t read/write package-lock.json', requiresValue: false },
      { name: '--package-lock-only', description: 'Only update package-lock.json', requiresValue: false },
      // Scripts and checks  
      { name: '--ignore-scripts', description: 'Skip running scripts', requiresValue: false },
      { name: '--foreground-scripts', description: 'Run scripts in foreground', requiresValue: false },
      { name: '--strict-peer-deps', description: 'Fail on peer dependency conflicts', requiresValue: false },
      // Audit and security
      { name: '--audit', description: 'Run security audit (default true)', requiresValue: false },
      { name: '--no-audit', description: 'Skip security audit', requiresValue: false },
      // Performance and behavior
      { name: '--dry-run', description: 'Preview without installing', requiresValue: false },
      { name: '--bin-links', description: 'Create symlinks for binaries (default true)', requiresValue: false },
      { name: '--no-bin-links', description: 'Don\'t create symlinks for binaries', requiresValue: false },
      { name: '--fund', description: 'Display funding info (default true)', requiresValue: false },
      { name: '--no-fund', description: 'Hide funding info', requiresValue: false },
      // Platform filters
      { name: '--before', description: 'Install versions published before date', requiresValue: true },
      { name: '--cpu', description: 'Filter by CPU architecture', requiresValue: true },
      { name: '--os', description: 'Filter by operating system', requiresValue: true },
      { name: '--libc', description: 'Filter by libc implementation', requiresValue: true },
      // Workspace support
      { name: '--workspace', aliases: ['-w'], description: 'Install in specific workspace', requiresValue: true },
      { name: '--workspaces', description: 'Install in all workspaces', requiresValue: false },
      { name: '--include-workspace-root', description: 'Include workspace root', requiresValue: false },
      { name: '--install-links', description: 'Install file: protocol deps as symlinks', requiresValue: false },
    ],
    mockOutput: '\nadded 1 package, and audited 2 packages in 3s\n\nfound 0 vulnerabilities',
  },
  {
    name: 'uninstall',
    aliases: ['remove', 'rm', 'r', 'un', 'unlink'],
    description: 'Remove packages',
    parameters: [
      { name: '--global', aliases: ['-g'], description: 'Uninstall globally', requiresValue: false },
      { name: '--save', aliases: ['-S'], description: 'Remove from dependencies', requiresValue: false },
      { name: '--save-dev', aliases: ['-D'], description: 'Remove from devDependencies', requiresValue: false },
      { name: '--workspace', aliases: ['-w'], description: 'Uninstall from specific workspace', requiresValue: true },
      { name: '--workspaces', description: 'Uninstall from all workspaces', requiresValue: false },
      { name: '--include-workspace-root', description: 'Include workspace root', requiresValue: false },
    ],
    mockOutput: '\nremoved 1 package, and audited 1 package in 1.5s\n\nfound 0 vulnerabilities',
  },
  {
    name: 'install-test',
    aliases: ['it'],
    description: 'Install package(s) and run tests',
    parameters: [
      // Same as install - inherits all install parameters
      { name: '--save-dev', aliases: ['-D'], description: 'Save to devDependencies', requiresValue: false },
      { name: '--global', aliases: ['-g'], description: 'Install globally', requiresValue: false },
      { name: '--dry-run', description: 'Preview without installing', requiresValue: false },
    ],
    mockOutput: '\nadded 1 package, and audited 2 packages in 3s\n\nfound 0 vulnerabilities\n\n> test\n> echo "Error: no test specified" && exit 1',
  },
  {
    name: 'install-ci-test',
    aliases: ['cit'],
    description: 'Clean install and run tests',
    parameters: [
      // Same as ci - inherits all ci parameters
      { name: '--ignore-scripts', description: 'Skip running scripts', requiresValue: false },
    ],
    mockOutput: '\nadded 145 packages in 5.3s\n\n> test\n> echo "Error: no test specified" && exit 1',
  },
  {
    name: 'update',
    aliases: ['up', 'upgrade', 'udpate'],
    description: 'Update packages',
    parameters: [
      { name: '--save', aliases: ['-S'], description: 'Save to dependencies', requiresValue: false },
      { name: '--save-prod', description: 'Save to dependencies', requiresValue: false },
      { name: '--no-save', description: 'Don\'t save to package.json', requiresValue: false },
      { name: '--save-dev', aliases: ['-D'], description: 'Save to devDependencies', requiresValue: false },
      { name: '--save-optional', description: 'Save to optionalDependencies', requiresValue: false },
      { name: '--save-peer', description: 'Save to peerDependencies', requiresValue: false },
      { name: '--save-bundle', description: 'Save to bundleDependencies', requiresValue: false },
      { name: '--global', aliases: ['-g'], description: 'Update globally', requiresValue: false },
      { name: '--install-strategy', description: 'Installation strategy', requiresValue: true },
      { name: '--legacy-bundling', description: 'Install with npm v2 bundling behavior', requiresValue: false },
      { name: '--global-style', description: 'Install packages into prefix without flattening', requiresValue: false },
      { name: '--omit', description: 'Omit dependency types', requiresValue: true },
      { name: '--include', description: 'Include dependency types', requiresValue: true },
      { name: '--strict-peer-deps', description: 'Fail on peer dependency conflicts', requiresValue: false },
      { name: '--no-package-lock', description: 'Don\'t update package-lock.json', requiresValue: false },
      { name: '--foreground-scripts', description: 'Run scripts in foreground', requiresValue: false },
      { name: '--ignore-scripts', description: 'Skip running scripts', requiresValue: false },
      { name: '--no-audit', description: 'Skip security audit', requiresValue: false },
      { name: '--no-bin-links', description: 'Don\'t create symlinks for binaries', requiresValue: false },
      { name: '--no-fund', description: 'Hide funding info', requiresValue: false },
      { name: '--dry-run', description: 'Preview without updating', requiresValue: false },
      { name: '--before', description: 'Only update to versions published before date', requiresValue: true },
      { name: '--workspace', aliases: ['-w'], description: 'Update in specific workspace', requiresValue: true },
      { name: '--workspaces', description: 'Update in all workspaces', requiresValue: false },
      { name: '--include-workspace-root', description: 'Include workspace root', requiresValue: false },
      { name: '--install-links', description: 'Install file: protocol deps as symlinks', requiresValue: false },
    ],
    mockOutput: '\nchanged 1 package, and audited 2 packages in 2.1s\n\nfound 0 vulnerabilities',
  },
  {
    name: 'list',
    aliases: ['ls', 'll', 'la'],
    description: 'List installed packages',
    parameters: [
      { name: '--all', aliases: ['-a'], description: 'Show all dependencies', requiresValue: false },
      { name: '--json', description: 'Output as JSON', requiresValue: false },
      { name: '--long', aliases: ['-l'], description: 'Show extended information', requiresValue: false },
      { name: '--parseable', aliases: ['-p'], description: 'Show parseable output', requiresValue: false },
      { name: '--global', aliases: ['-g'], description: 'List global packages', requiresValue: false },
      { name: '--depth', description: 'Max depth of tree', requiresValue: true },
      { name: '--omit', description: 'Omit dependency types', requiresValue: true },
      { name: '--include', description: 'Include dependency types', requiresValue: true },
      { name: '--link', description: 'Show linked packages only', requiresValue: false },
      { name: '--package-lock-only', description: 'Only use package-lock.json', requiresValue: false },
      { name: '--no-unicode', description: 'Don\'t use unicode characters', requiresValue: false },
      { name: '--workspace', aliases: ['-w'], description: 'List in specific workspace', requiresValue: true },
      { name: '--workspaces', aliases: ['-ws'], description: 'List in all workspaces', requiresValue: false },
      { name: '--include-workspace-root', description: 'Include workspace root', requiresValue: false },
      { name: '--install-links', description: 'Include symlinked packages', requiresValue: false },
    ],
    mockOutput: 'my-project@1.0.0\n├── lodash@4.17.21\n└── express@4.18.2\n',
  },
  {
    name: 'll',
    description: 'List installed packages (long format)',
    parameters: [
      { name: '--global', aliases: ['-g'], description: 'List global packages', requiresValue: false },
      { name: '--depth', description: 'Max depth of tree', requiresValue: true },
    ],
    mockOutput: 'my-project@1.0.0\n├── lodash@4.17.21 (latest: 4.17.21)\n│   Description: Lodash modular utilities\n└── express@4.18.2 (latest: 4.18.2)\n    Description: Fast, unopinionated, minimalist web framework',
  },
  {
    name: 'run',
    aliases: ['run-script', 'rum', 'urn'],
    description: 'List available scripts',
    parameters: [
      { name: 'build', description: 'Run the build script', requiresValue: false },
      { name: '--silent', description: 'Suppress output', requiresValue: false },
    ],
    mockOutput: 'Lifecycle scripts included in my-project@1.0.0:\n  test\n    echo "Error: no test specified"\n  start\n    node index.js\n\nAvailable scripts:\n  build\n    webpack --mode production',
  },
  {
    name: 'test',
    aliases: ['t', 'tst'],
    description: 'Run tests',
    parameters: [],
    mockOutput: '\n> my-project@1.0.0 test\n> jest\n\nPASS  ./app.test.js\n  ✓ renders correctly (5ms)\n\nTest Suites: 1 passed, 1 total\nTests:       1 passed, 1 total',
  },
  {
    name: 'start',
    description: 'Start the application',
    parameters: [],
    mockOutput: '\n> my-project@1.0.0 start\n> node index.js\n\nServer is running on port 3000',
  },
  {
    name: 'stop',
    description: 'Stop a package',
    parameters: [],
    mockOutput: '\n> my-project@1.0.0 stop\n> node stop.js',
  },
  {
    name: 'restart',
    description: 'Restart a package',
    parameters: [],
    mockOutput: '\n> my-project@1.0.0 restart\n> npm stop && npm start',
  },
  {
    name: 'version',
    aliases: ['verison'],
    description: 'Bump package version or show npm/node versions',
    parameters: [
      { name: '--json', description: 'Output as JSON', requiresValue: false },
      { name: '--allow-same-version', description: 'Allow bumping to same version', requiresValue: false },
      { name: '--no-commit-hooks', description: 'Skip git commit hooks', requiresValue: false },
      { name: '--no-git-tag-version', description: 'Don\'t tag version in git', requiresValue: false },
      { name: '--preid', description: 'Prerelease identifier', requiresValue: true },
      { name: '--sign-git-tag', description: 'Sign git tag', requiresValue: false },
      { name: '--workspace', aliases: ['-w'], description: 'Version specific workspace', requiresValue: true },
      { name: '--workspaces', description: 'Version all workspaces', requiresValue: false },
      { name: '--include-workspace-root', description: 'Include workspace root', requiresValue: false },
      { name: '--no-workspaces-update', description: 'Don\'t update workspace dependencies', requiresValue: false },
    ],
    mockOutput: 'v1.0.1',
  },
  {
    name: 'publish',
    description: 'Publish a package to registry',
    parameters: [
      { name: '--tag', description: 'Tag to publish', requiresValue: true },
      { name: '--access', description: 'Set access level (public/restricted)', requiresValue: true },
      { name: '--dry-run', description: 'Test without publishing', requiresValue: false },
      { name: '--otp', description: 'One-time password for 2FA', requiresValue: true },
      { name: '--workspace', aliases: ['-w'], description: 'Publish specific workspace', requiresValue: true },
      { name: '--workspaces', aliases: ['-ws'], description: 'Publish all workspaces', requiresValue: false },
      { name: '--include-workspace-root', description: 'Include workspace root', requiresValue: false },
      { name: '--provenance', description: 'Generate provenance statements', requiresValue: false },
      { name: '--provenance-file', description: 'Provenance file path', requiresValue: true },
    ],
    mockOutput: 'npm notice \nnpm notice 📦  my-package@1.0.0\nnpm notice === Tarball Contents ===\nnpm notice 1.1kB package.json\nnpm notice === Tarball Details ===\nnpm notice name:          my-package\nnpm notice version:       1.0.0\nnpm notice filename:      my-package-1.0.0.tgz\nnpm notice package size:  512 B\nnpm notice unpacked size: 1.1 kB\nnpm notice total files:   1\nnpm notice \n+ my-package@1.0.0',
  },
  {
    name: 'unpublish',
    description: 'Remove a package from the registry',
    parameters: [
      { name: '--force', aliases: ['-f'], description: 'Force unpublish', requiresValue: false },
    ],
    mockOutput: '- my-package@1.0.0',
  },
  {
    name: 'search',
    aliases: ['s', 'se', 'find'],
    description: 'Search for packages',
    parameters: [
      { name: '--json', description: 'Output as JSON', requiresValue: false },
      { name: '--color', description: 'Enable color output', requiresValue: false },
      { name: '--no-color', description: 'Disable color output', requiresValue: false },
      { name: '--parseable', aliases: ['-p'], description: 'Show parseable output', requiresValue: false },
      { name: '--no-description', description: 'Don\'t show descriptions', requiresValue: false },
      { name: '--searchlimit', description: 'Limit number of results', requiresValue: true },
      { name: '--searchopts', description: 'Options passed to search', requiresValue: true },
      { name: '--searchexclude', description: 'Exclude from search', requiresValue: true },
      { name: '--registry', description: 'Registry URL', requiresValue: true },
      { name: '--prefer-online', description: 'Prefer online registry', requiresValue: false },
      { name: '--prefer-offline', description: 'Prefer offline cache', requiresValue: false },
      { name: '--offline', description: 'Force offline mode', requiresValue: false },
    ],
    mockOutput: 'NAME                      | DESCRIPTION          | AUTHOR          | DATE       | VERSION\nlodash                    | Lodash modular…      | =jdalton…       | 2021-02-20 | 4.17.21\nunderscore                | JavaScript\'s…         | =jashkenas      | 2023-10-18 | 1.13.6',
  },
  {
    name: 'view',
    aliases: ['info', 'show', 'v'],
    description: 'View registry info',
    parameters: [
      { name: '--json', description: 'Output as JSON', requiresValue: false },
      { name: '--workspace', aliases: ['-w'], description: 'View specific workspace', requiresValue: true },
      { name: '--workspaces', description: 'View all workspaces', requiresValue: false },
      { name: '--include-workspace-root', description: 'Include workspace root', requiresValue: false },
    ],
    mockOutput: 'lodash@4.17.21 | MIT | deps: none | versions: 114\nLodash modular utilities.\nhttps://lodash.com/\n\nkeywords: modules, stdlib, util\n\ndist\n.tarball: https://registry.npmjs.org/lodash/-/lodash-4.17.21.tgz\n.shasum: 679591c564c3bffaae8454cf0b3df370c3d6911c',
  },
  {
    name: 'outdated',
    description: 'Check for outdated packages',
    parameters: [
      { name: '--all', aliases: ['-a'], description: 'Check all packages', requiresValue: false },
      { name: '--json', description: 'Output as JSON', requiresValue: false },
      { name: '--long', aliases: ['-l'], description: 'Show extended information', requiresValue: false },
      { name: '--parseable', aliases: ['-p'], description: 'Show parseable output', requiresValue: false },
      { name: '--global', aliases: ['-g'], description: 'Check global packages', requiresValue: false },
      { name: '--before', description: 'Only show versions published before date', requiresValue: true },
      { name: '--workspace', aliases: ['-w'], description: 'Check specific workspace', requiresValue: true },
      { name: '--workspaces', description: 'Check all workspaces', requiresValue: false },
    ],
    mockOutput: 'Package       Current  Wanted  Latest  Location\nlodash        4.17.20  4.17.21 4.17.21 node_modules/lodash',
  },
  {
    name: 'audit',
    description: 'Run security audit',
    parameters: [
      { name: '--audit-level', description: 'Minimum level to exit with error (info, low, moderate, high, critical)', requiresValue: true },
      { name: '--dry-run', description: 'Preview fixes without applying', requiresValue: false },
      { name: '--force', aliases: ['-f'], description: 'Force install of recommended updates', requiresValue: false },
      { name: '--json', description: 'Output as JSON', requiresValue: false },
      { name: '--package-lock-only', description: 'Only use package-lock.json', requiresValue: false },
      { name: '--no-package-lock', description: 'Don\'t read package-lock.json', requiresValue: false },
      { name: '--omit', description: 'Omit dependency types', requiresValue: true },
      { name: '--include', description: 'Include dependency types', requiresValue: true },
      { name: '--foreground-scripts', description: 'Run scripts in foreground', requiresValue: false },
      { name: '--ignore-scripts', description: 'Skip running scripts', requiresValue: false },
      { name: '--workspace', aliases: ['-w'], description: 'Audit specific workspace', requiresValue: true },
      { name: '--workspaces', aliases: ['-ws'], description: 'Audit all workspaces', requiresValue: false },
      { name: '--include-workspace-root', description: 'Include workspace root', requiresValue: false },
      { name: '--install-links', description: 'Install file: protocol deps as symlinks', requiresValue: false },
    ],
    mockOutput: 'found 0 vulnerabilities',
  },
  {
    name: 'config',
    aliases: ['c'],
    description: 'Manage npm configuration',
    parameters: [
      { name: '--json', description: 'Output as JSON', requiresValue: false },
      { name: '--global', aliases: ['-g'], description: 'Use global config', requiresValue: false },
      { name: '--editor', description: 'Editor for config edit', requiresValue: true },
      { name: '--location', aliases: ['-L'], description: 'Config location (global, user, project)', requiresValue: true },
      { name: '--long', description: 'Show extended information', requiresValue: false },
    ],
    mockOutput: '; "user" config from C:\\Users\\user\\.npmrc\n\ninit-author-name = "Your Name"\nregistry = "https://registry.npmjs.org/"',
  },
  {
    name: 'get',
    description: 'Get a config value',
    parameters: [
      { name: '--global', aliases: ['-g'], description: 'Get from global config', requiresValue: false },
      { name: '--location', description: 'Config location', requiresValue: true },
    ],
    mockOutput: 'https://registry.npmjs.org/',
  },
  {
    name: 'set',
    description: 'Set a config value',
    parameters: [
      { name: '--global', aliases: ['-g'], description: 'Set in global config', requiresValue: false },
      { name: '--location', description: 'Config location', requiresValue: true },
    ],
    mockOutput: '',
  },
  {
    name: 'cache',
    description: 'Manage npm cache',
    parameters: [
      { name: 'clean', description: 'Clean cache', requiresValue: false },
      { name: 'verify', description: 'Verify cache', requiresValue: false },
      { name: '--force', aliases: ['-f'], description: 'Force operation', requiresValue: false },
    ],
    mockOutput: 'Cache verified and compressed\nContent verified: 1234 (56.7 MB)\nIndex entries: 5678\nFinished in 3.45s',
  },
  {
    name: 'doctor',
    description: 'Check npm environment',
    parameters: [],
    mockOutput: 'Check                               Value   Recommendation\nnpm ping                            ok      \nnpm -v                              v10.2.4 Use npm v10.8.2\nnode -v                             v20.11.0 Use node v20.15.0\nnpm config get registry             ok      using default registry\nwhich git                           ok      C:\\Program Files\\Git\\cmd\\git.EXE',
  },
  {
    name: 'prune',
    description: 'Remove extraneous packages',
    parameters: [
      { name: '--omit', description: 'Omit dependency types (use instead of --production)', requiresValue: true },
      { name: '--include', description: 'Include dependency types', requiresValue: true },
      { name: '--dry-run', description: 'Show what would be removed', requiresValue: false },
      { name: '--json', description: 'Output as JSON', requiresValue: false },
      { name: '--foreground-scripts', description: 'Run scripts in foreground', requiresValue: false },
      { name: '--ignore-scripts', description: 'Skip running scripts', requiresValue: false },
      { name: '--workspace', aliases: ['-w'], description: 'Prune in specific workspace', requiresValue: true },
      { name: '--workspaces', aliases: ['-ws'], description: 'Prune in all workspaces', requiresValue: false },
      { name: '--include-workspace-root', description: 'Include workspace root', requiresValue: false },
      { name: '--install-links', description: 'Install file: protocol deps as symlinks', requiresValue: false },
    ],
    mockOutput: 'removed 15 packages in 1.2s',
  },
  {
    name: 'dedupe',
    aliases: ['ddp'],
    description: 'Reduce package duplication',
    parameters: [
      { name: '--install-strategy', description: 'Installation strategy', requiresValue: true },
      { name: '--legacy-bundling', description: 'Install with npm v2 bundling behavior', requiresValue: false },
      { name: '--global-style', description: 'Install packages into prefix without flattening', requiresValue: false },
      { name: '--strict-peer-deps', description: 'Fail on peer dependency conflicts', requiresValue: false },
      { name: '--no-package-lock', description: 'Don\'t update package-lock.json', requiresValue: false },
      { name: '--omit', description: 'Omit dependency types', requiresValue: true },
      { name: '--include', description: 'Include dependency types', requiresValue: true },
      { name: '--ignore-scripts', description: 'Skip running scripts', requiresValue: false },
      { name: '--no-audit', description: 'Skip security audit', requiresValue: false },
      { name: '--no-bin-links', description: 'Don\'t create symlinks for binaries', requiresValue: false },
      { name: '--no-fund', description: 'Hide funding info', requiresValue: false },
      { name: '--dry-run', description: 'Preview without deduping', requiresValue: false },
      { name: '--workspace', aliases: ['-w'], description: 'Dedupe in specific workspace', requiresValue: true },
      { name: '--workspaces', aliases: ['-ws'], description: 'Dedupe in all workspaces', requiresValue: false },
      { name: '--include-workspace-root', description: 'Include workspace root', requiresValue: false },
      { name: '--install-links', description: 'Install file: protocol deps as symlinks', requiresValue: false },
    ],
    mockOutput: 'removed 3 packages, and changed 5 packages in 2s',
  },
  {
    name: 'find-dupes',
    description: 'Find duplication in package tree',
    parameters: [
      { name: '--install-strategy', description: 'Installation strategy', requiresValue: true },
      { name: '--legacy-bundling', description: 'Install with npm v2 bundling behavior', requiresValue: false },
      { name: '--global-style', description: 'Install packages into prefix without flattening', requiresValue: false },
      { name: '--strict-peer-deps', description: 'Fail on peer dependency conflicts', requiresValue: false },
      { name: '--no-package-lock', description: 'Don\'t read package-lock.json', requiresValue: false },
      { name: '--omit', description: 'Omit dependency types', requiresValue: true },
      { name: '--include', description: 'Include dependency types', requiresValue: true },
      { name: '--no-fund', description: 'Hide funding info', requiresValue: false },
      { name: '--workspace', aliases: ['-w'], description: 'Find dupes in specific workspace', requiresValue: true },
      { name: '--workspaces', aliases: ['-ws'], description: 'Find dupes in all workspaces', requiresValue: false },
      { name: '--include-workspace-root', description: 'Include workspace root', requiresValue: false },
      { name: '--install-links', description: 'Include symlinked packages', requiresValue: false },
    ],
    mockOutput: 'Found 3 duplicate packages:\nlodash@4.17.21\nunderscore@1.13.6\nmoment@2.29.4',
  },
  {
    name: 'link',
    aliases: ['ln'],
    description: 'Create a symlink to a package',
    parameters: [
      { name: '--save', aliases: ['-S'], description: 'Save to dependencies', requiresValue: false },
      { name: '--save-prod', description: 'Save to dependencies', requiresValue: false },
      { name: '--no-save', description: 'Don\'t save to package.json', requiresValue: false },
      { name: '--save-dev', aliases: ['-D'], description: 'Save to devDependencies', requiresValue: false },
      { name: '--save-exact', aliases: ['-E'], description: 'Save exact version', requiresValue: false },
      { name: '--save-optional', description: 'Save to optionalDependencies', requiresValue: false },
      { name: '--save-peer', description: 'Save to peerDependencies', requiresValue: false },
      { name: '--save-bundle', description: 'Save to bundleDependencies', requiresValue: false },
      { name: '--global', aliases: ['-g'], description: 'Link globally', requiresValue: false },
      { name: '--install-strategy', description: 'Installation strategy', requiresValue: true },
      { name: '--legacy-bundling', description: 'Install with npm v2 bundling behavior', requiresValue: false },
      { name: '--global-style', description: 'Install packages into prefix without flattening', requiresValue: false },
      { name: '--strict-peer-deps', description: 'Fail on peer dependency conflicts', requiresValue: false },
      { name: '--no-package-lock', description: 'Don\'t update package-lock.json', requiresValue: false },
      { name: '--omit', description: 'Omit dependency types', requiresValue: true },
      { name: '--include', description: 'Include dependency types', requiresValue: true },
      { name: '--ignore-scripts', description: 'Skip running scripts', requiresValue: false },
      { name: '--no-audit', description: 'Skip security audit', requiresValue: false },
      { name: '--no-bin-links', description: 'Don\'t create symlinks for binaries', requiresValue: false },
      { name: '--no-fund', description: 'Hide funding info', requiresValue: false },
      { name: '--dry-run', description: 'Preview without linking', requiresValue: false },
      { name: '--workspace', aliases: ['-w'], description: 'Link in specific workspace', requiresValue: true },
      { name: '--workspaces', aliases: ['-ws'], description: 'Link in all workspaces', requiresValue: false },
      { name: '--include-workspace-root', description: 'Include workspace root', requiresValue: false },
      { name: '--install-links', description: 'Install file: protocol deps as symlinks', requiresValue: false },
    ],
    mockOutput: 'C:\\Users\\user\\AppData\\Roaming\\npm\\node_modules\\my-package -> C:\\Users\\user\\my-package',
  },
  {
    name: 'ci',
    aliases: ['clean-install', 'ic', 'install-clean', 'isntall-clean'],
    description: 'Clean install from package-lock',
    parameters: [
      { name: '--install-strategy', description: 'Installation strategy', requiresValue: true },
      { name: '--legacy-bundling', description: 'Install with npm v2 bundling behavior', requiresValue: false },
      { name: '--global-style', description: 'Install packages into prefix without flattening', requiresValue: false },
      { name: '--omit', description: 'Omit dependency types', requiresValue: true },
      { name: '--strict-peer-deps', description: 'Fail on peer dependency conflicts', requiresValue: false },
      { name: '--foreground-scripts', description: 'Run scripts in foreground', requiresValue: false },
      { name: '--ignore-scripts', description: 'Skip running scripts', requiresValue: false },
      { name: '--no-audit', description: 'Skip security audit', requiresValue: false },
      { name: '--dry-run', description: 'Preview without installing', requiresValue: false },
      { name: '--no-fund', description: 'Hide funding info', requiresValue: false },
      { name: '--workspace', aliases: ['-w'], description: 'Install in specific workspace', requiresValue: true },
      { name: '--workspaces', description: 'Install in all workspaces', requiresValue: false },
      { name: '--include-workspace-root', description: 'Include workspace root', requiresValue: false },
    ],
    mockOutput: '\nadded 145 packages in 5.3s',
  },
  {
    name: 'exec',
    aliases: ['x'],
    description: 'Execute a package binary',
    parameters: [
      { name: '--package', aliases: ['-p'], description: 'Package to execute', requiresValue: true },
      { name: '--call', aliases: ['-c'], description: 'Command string to execute', requiresValue: true },
      { name: '--workspace', aliases: ['-w'], description: 'Execute in specific workspace', requiresValue: true },
      { name: '--workspaces', description: 'Execute in all workspaces', requiresValue: false },
      { name: '--include-workspace-root', description: 'Include workspace root', requiresValue: false },
    ],
    mockOutput: 'Package executed successfully',
  },
  {
    name: 'explain',
    aliases: ['why'],
    description: 'Explain why a package is installed',
    parameters: [],
    mockOutput: 'lodash@4.17.21\nnode_modules/lodash\n  lodash@"^4.17.0" from my-project@1.0.0\n  node_modules/my-project',
  },
  {
    name: 'fund',
    description: 'Display funding information',
    parameters: [
      { name: '--json', description: 'Output as JSON', requiresValue: false },
    ],
    mockOutput: 'my-project@1.0.0\n├── https://github.com/sponsors/author1\n│   └── package1@1.0.0\n└── https://opencollective.com/project2\n    └── package2@2.0.0\n\n2 packages are looking for funding',
  },
  {
    name: 'help',
    aliases: ['?'],
    description: 'Get help on npm',
    parameters: [],
    mockOutput: 'npm <command>\n\nUsage:\n\nnpm install        install all the dependencies in your project\nnpm install <foo>  add the <foo> dependency to your project\nnpm test           run this project\'s tests\nnpm run <foo>      run the script named <foo>\nnpm <command> -h   quick help on <command>\nnpm -l             display usage info for all commands',
  },
  {
    name: 'help-search',
    description: 'Search npm help documentation',
    parameters: [],
    mockOutput: 'Top hits for "install"\n———————————————————————————————————\nnpm install\n  Install a package',
  },
  {
    name: 'hook',
    description: 'Manage registry hooks',
    parameters: [
      { name: 'add', description: 'Add hook', requiresValue: true },
      { name: 'ls', description: 'List hooks', requiresValue: false },
      { name: 'rm', description: 'Remove hook', requiresValue: true },
    ],
    mockOutput: 'No hooks configured',
  },
  {
    name: 'org',
    description: 'Manage organization',
    parameters: [
      { name: 'set', description: 'Set organization property', requiresValue: true },
      { name: 'ls', description: 'List organizations', requiresValue: false },
    ],
    mockOutput: '@myorg',
  },
  {
    name: 'owner',
    aliases: ['author'],
    description: 'Manage package owners',
    parameters: [
      { name: 'add', description: 'Add owner', requiresValue: true },
      { name: 'rm', description: 'Remove owner', requiresValue: true },
      { name: 'ls', description: 'List owners', requiresValue: false },
    ],
    mockOutput: 'username <user@example.com>',
  },
  {
    name: 'pack',
    description: 'Create a tarball from a package',
    parameters: [
      { name: '--dry-run', description: 'Test without creating tarball', requiresValue: false },
    ],
    mockOutput: 'npm notice \nnpm notice 📦  my-package@1.0.0\nnpm notice === Tarball Contents ===\nnpm notice 1.1kB package.json\nnpm notice 524B  index.js\nnpm notice === Tarball Details ===\nnpm notice name:          my-package\nnpm notice version:       1.0.0\nnpm notice filename:      my-package-1.0.0.tgz\nnpm notice package size:  1.2 kB\nnpm notice unpacked size: 1.6 kB\nnpm notice total files:   2\nnpm notice \nmy-package-1.0.0.tgz',
  },
  {
    name: 'ping',
    description: 'Ping npm registry',
    parameters: [],
    mockOutput: 'Ping success: wrote to registry in 256ms',
  },
  {
    name: 'prefix',
    description: 'Display prefix',
    parameters: [
      { name: '-g', aliases: ['--global'], description: 'Display global prefix', requiresValue: false },
    ],
    mockOutput: 'C:\\Users\\user\\project',
  },
  {
    name: 'profile',
    description: 'Manage npm profile',
    parameters: [
      { name: 'get', description: 'Get profile property', requiresValue: false },
      { name: 'set', description: 'Set profile property', requiresValue: true },
    ],
    mockOutput: '┌─────────────┬────────────────────┐\n│ name        │ username           │\n├─────────────┼────────────────────┤\n│ email       │ user@example.com   │\n├─────────────┼────────────────────┤\n│ created     │ 2023-01-15         │\n└─────────────┴────────────────────┘',
  },
  {
    name: 'rebuild',
    aliases: ['rb'],
    description: 'Rebuild a package',
    parameters: [],
    mockOutput: 'rebuilt dependencies',
  },
  {
    name: 'repo',
    description: 'Open package repository in browser',
    parameters: [],
    mockOutput: 'Opening https://github.com/lodash/lodash in browser',
  },
  {
    name: 'root',
    description: 'Display npm root',
    parameters: [
      { name: '-g', aliases: ['--global'], description: 'Display global root', requiresValue: false },
    ],
    mockOutput: 'C:\\Users\\user\\project\\node_modules',
  },
  {
    name: 'set-script',
    description: 'Set a package.json script',
    parameters: [],
    mockOutput: 'Added script "build": "tsc"',
  },
  {
    name: 'shrinkwrap',
    description: 'Lock dependencies',
    parameters: [],
    mockOutput: 'wrote npm-shrinkwrap.json',
  },
  {
    name: 'star',
    description: 'Mark a package as favorite',
    parameters: [],
    mockOutput: '★ lodash',
  },
  {
    name: 'stars',
    description: 'View starred packages',
    parameters: [],
    mockOutput: 'lodash\nexpress\nreact',
  },
  {
    name: 'team',
    description: 'Manage organization teams',
    parameters: [
      { name: 'create', description: 'Create team', requiresValue: true },
      { name: 'destroy', description: 'Destroy team', requiresValue: true },
      { name: 'add', description: 'Add user to team', requiresValue: true },
      { name: 'rm', description: 'Remove user from team', requiresValue: true },
      { name: 'ls', description: 'List teams', requiresValue: false },
    ],
    mockOutput: '@myorg:developers\n@myorg:admins',
  },
  {
    name: 'token',
    description: 'Manage authentication tokens',
    parameters: [
      { name: 'list', description: 'List tokens', requiresValue: false },
      { name: 'create', description: 'Create token', requiresValue: false },
      { name: 'revoke', description: 'Revoke token', requiresValue: true },
    ],
    mockOutput: '┌────────┬─────────┬────────────┬──────────┐\n│ token  │ created │ readonly   │ CIDR     │\n├────────┼─────────┼────────────┼──────────┤\n│ abc123 │ 2023-01 │ no         │          │\n└────────┴─────────┴────────────┴──────────┘',
  },
  {
    name: 'unstar',
    description: 'Unmark a package as favorite',
    parameters: [],
    mockOutput: '☆ lodash',
  },
  {
    name: 'whoami',
    description: 'Display npm username',
    parameters: [],
    mockOutput: 'username',
  },
  {
    name: 'access',
    description: 'Manage package access',
    parameters: [
      { name: 'public', description: 'Make package public', requiresValue: false },
      { name: 'restricted', description: 'Make package restricted', requiresValue: false },
      { name: 'grant', description: 'Grant access', requiresValue: true },
      { name: 'revoke', description: 'Revoke access', requiresValue: true },
    ],
    mockOutput: 'Set package access to public',
  },
  {
    name: 'adduser',
    aliases: ['add-user'],
    description: 'Add a registry user account',
    parameters: [
      { name: '--registry', description: 'Registry URL', requiresValue: true },
      { name: '--scope', description: 'Scope for authentication', requiresValue: true },
      { name: '--auth-type', description: 'Authentication type (legacy, web, oauth)', requiresValue: true },
    ],
    mockOutput: 'Logged in as username on https://registry.npmjs.org/.',
  },
  {
    name: 'login',
    description: 'Login to a registry user account',
    parameters: [
      { name: '--registry', description: 'Registry URL', requiresValue: true },
      { name: '--scope', description: 'Scope for authentication', requiresValue: true },
      { name: '--auth-type', description: 'Authentication type (legacy, web, oauth)', requiresValue: true },
    ],
    mockOutput: 'Logged in as username on https://registry.npmjs.org/.',
  },
  {
    name: 'logout',
    description: 'Log out of the registry',
    parameters: [
      { name: '--registry', description: 'Registry URL', requiresValue: true },
      { name: '--scope', description: 'Scope for authentication', requiresValue: true },
    ],
    mockOutput: 'Logged out from https://registry.npmjs.org/',
  },
  {
    name: 'bugs',
    aliases: ['issues'],
    description: 'Open package bugs page in browser',
    parameters: [],
    mockOutput: 'Opening https://github.com/lodash/lodash/issues in browser',
  },
  {
    name: 'docs',
    aliases: ['home'],
    description: 'Open package documentation in browser',
    parameters: [],
    mockOutput: 'Opening https://lodash.com/ in browser',
  },
  {
    name: 'edit',
    description: 'Edit an installed package',
    parameters: [],
    mockOutput: 'Opening package in editor',
  },
  {
    name: 'explore',
    description: 'Browse an installed package',
    parameters: [],
    mockOutput: 'Spawning shell in package directory',
  },
  {
    name: 'diff',
    description: 'Show package diff',
    parameters: [],
    mockOutput: 'diff --git a/index.js b/index.js\nindex 1234567..abcdefg 100644\n--- a/index.js\n+++ b/index.js\n@@ -1,3 +1,3 @@\n-console.log("old");\n+console.log("new");',
  },
  {
    name: 'dist-tag',
    aliases: ['dist-tags'],
    description: 'Modify package distribution tags',
    parameters: [
      { name: 'add', description: 'Add tag', requiresValue: true },
      { name: 'rm', description: 'Remove tag', requiresValue: true },
      { name: 'ls', description: 'List tags', requiresValue: false },
    ],
    mockOutput: 'latest: 1.0.0\nbeta: 1.1.0-beta.0',
  },
  {
    name: 'deprecate',
    description: 'Deprecate a package version',
    parameters: [
      { name: '--registry', description: 'Registry URL', requiresValue: true },
      { name: '--otp', description: 'One-time password for 2FA', requiresValue: true },
    ],
    mockOutput: 'Deprecated my-package@1.0.0',
  },
  {
    name: 'undeprecate',
    description: 'Undeprecate a package version',
    parameters: [
      { name: '--registry', description: 'Registry URL', requiresValue: true },
      { name: '--otp', description: 'One-time password for 2FA', requiresValue: true },
    ],
    mockOutput: 'Undeprecated my-package@1.0.0',
  },
  {
    name: 'completion',
    description: 'Tab completion for npm',
    parameters: [],
    mockOutput: '###-begin-npm-completion-###\n# npm command completion script',
  },
  {
    name: 'bin',
    description: 'Display npm bin folder',
    parameters: [
      { name: '-g', aliases: ['--global'], description: 'Display global bin folder', requiresValue: false },
    ],
    mockOutput: 'C:\\Users\\user\\project\\node_modules\\.bin',
  },
  {
    name: 'pkg',
    description: 'Manage package.json',
    parameters: [
      { name: 'get', description: 'Get a field', requiresValue: true },
      { name: 'set', description: 'Set a field', requiresValue: true },
      { name: 'delete', description: 'Delete a field', requiresValue: true },
    ],
    mockOutput: '{\n  "name": "my-project",\n  "version": "1.0.0"\n}',
  },
  {
    name: 'query',
    description: 'Query installed packages with CSS selectors',
    parameters: [],
    mockOutput: '[\n  {\n    "name": "lodash",\n    "version": "4.17.21"\n  }\n]',
  },
  {
    name: 'sbom',
    description: 'Generate a Software Bill of Materials',
    parameters: [
      { name: '--format', description: 'Output format', requiresValue: true },
    ],
    mockOutput: '{\n  "bomFormat": "CycloneDX",\n  "specVersion": "1.4",\n  "version": 1,\n  "components": []\n}',
  },
];
